# Configure the Large Language Model Api calls 
LLMConfig:
  temperature: 0
  model: "text-davinci-003"
  max_tokens: 250
# Configure how the pdf file texts should be chunked into Node texts
SimpleNodeParser:
  chunk_size: 1024
  chunk_overlap: 20
# Specify how many contexts to retrieve in the retrieval step 
QueryEngineConfig:
  similarity_top_k: 3
# Configure the prompt for response synthesis 
PromptHelper:
  context_window: 4096
  chunk_overlap_ratio: 0.1
  chunk_size_limit: null
# Specify the SentenceTransformer model for semantic clustering of responses 
ClusteringConfig:
  SentenceTransformerModel: "all-mpnet-base-v2"
# Specify the Config for the Esco Faiss index skill query API 
EscoSkillApiConfig:
  index_name: esco_skill_index
  top_k: 1
# This is a config for the Api to extract a semicolon separated list of skills from a Skill description text
SkillsToListConfig:
  llm_model_name: "text-davinci-003"
  temperature: 0.0
  prompt_template: skill_list_prompt.txt
